version: '3.8'

services:
  app:
    build:
      context: C:\Users\haykb\Desktop\Study\HR_project\HR_Management_System\backend\hrmanagement
      dockerfile: Dockerfile
    image: hr_management_app
    ports:
      - "8081:8080" # Host port 8081 -> Container port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hr_management_db:5432/hr_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:14-alpine
    container_name: hr_management_db
    environment:
      POSTGRES_DB: hr_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  frontend:
    build:
      context: C:\Users\haykb\Desktop\Study\HR_project\HR_Management_System\frontend
      dockerfile: Dockerfile
    image: hr_management_frontend
    ports:
      - "3000:3000" # Host port 3000 -> Container port 3000
    environment:
      - CHOKIDAR_USEPOLLING=true # Для hot-reload в Docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - default
    depends_on:
      - app

volumes:
  postgres_data:

networks:
  default:
    name: hrmanagement_default